- hosts: 127.0.0.1
  tasks:
   - ec2_instance:
       region: us-east-1
       image_id: ami-0be2609ba883822ec
       vpc_subnet_id: subnet-0d5fa23c
       security_group: sg-d01642ef
       key_name: awseducate
       name: ansible_launched_os
       state: present
       aws_access_key: #Add your Access key
       aws_secret_key: # Add your Secret Key
       aws_security_token: # Add your Security Token
     register: x
   - debug:
       var:  x
  
