- name: Configuring Docker
  hosts: all
  tasks:
  - name: Adding Docker repository
    yum_repository:
      name: Docker
      description: Docker Repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      gpgcheck: no
  - name: Installing Docker package
    package:
      name:  "docker-ce-18.09.1-3.el7.x86_64"
      state: present
  - name: Starting docker service
    service:
      name: "docker"
      state: started
      enabled: yes
  - name: Installing Docker SDK for python3
    command: pip3 install docker
